name: Deploy Folio App

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - run: yarn run build
      - run: yarn run pack
      - uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - uses: "google-github-actions/setup-gcloud@v0"
      - run: "gsutil cp folio.tar.gz gs://${{ secrets.GOOGLE_BUCKET }}/"
